### root logger option ###
log4j.rootLogger=info
### appenders

# R is the RollingFileAppender that outputs to a rolling log 
# file called rolling_log_file.log.
#TradeLoal log
log4j.logger.elecVoucherSys=info, R
log4j.appender.R=org.apache.log4j.DailyRollingFileAppender
log4j.appender.R.File=log/elecVoucherSys.log
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.R.bufferedIO=false
log4j.appender.R.DatePattern='.'yyyyMMdd

log4j.logger.com.aktech=info, E
log4j.appender.E=org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File=log/elecVoucherSys.log
log4j.appender.E.layout=org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.E.bufferedIO=false
log4j.appender.E.DatePattern='.'yyyyMMdd

log4j.logger.cn.com.agree.elecVoucher=info, D
log4j.appender.D=org.apache.log4j.DailyRollingFileAppender
log4j.appender.D.File=log/localService.log
log4j.appender.D.layout=org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.D.bufferedIO=false
log4j.appender.D.DatePattern='.'yyyyMMdd