Name=缺省
Value.Color.Border=192,192,192
Value.Color.Disable=151,136,147
Value.Color.Focus=192,192,192
Value.Color.Hover=48,196,243
Value.Color.Light=175,175,175
Value.Color.Text=0,0,0
Value.Color.Widget=232,232,232
Value.Image.DynamicBtn_Dynamic=按钮.png
Value.Image.tool_快速查询=快速查询.png
Value.Image.tool_系统帮助=系统帮助.png
Value.Image.tool_辅助工具=辅助工具.png
Value.Image.tool_联网核查=联网核查.png
Value.Image.tool_系统设置=系统设置.png
Value.Image.tool_退出=退出.png
Value.Image.tool_锁屏=锁屏.png
Value.Image.tool_小标题=logo1.png
Value.Image.主背景=主背景.png
Value.Image.底边背景=底边背景.png
Value.Image.标题背景=标题背景.png
Value.Image.登录背景=登录背景.png
Value.Image.锁屏背景=锁屏背景.png
Value.Integer.Alpha=250
Value.Integer.悬浮Alpha=200

Value.Image.分隔条=splic.png
Value.Image.标题=logo.png
Value.Image.面板底图=backpanel.png
Value.Image.交易搜索框背景=tradeCode.png


#多交易容器
Value.Image.交易容器=主背景.png

# 这个是配置动态按钮的文本颜色
Value.Color.FocusedButtonText=255,255,255
Value.Color.HoveredButtonText=255,255,255
Value.Color.OrdinaryButtonText=255,255,255

# 这个是配置动态按钮的图片
Value.Image.DynamicBtn_Focus_Dynamic=ordinaryButton.png
Value.Image.DynamicBtn_Hover_Dynamic=hoveredButton.png

Value.Color.DynamicBtn_Text=255,255,255
Value.Font.DynamicBtn_Font=微软雅黑
Value.Integer.DynamicBtn_FontSize=9
Value.Integer.DynamicBtn_FontStyle=1

#登录
Value.Image.DynamicBtn_登录_Dynamic=login_normal.png
Value.Image.DynamicBtn_登录_Hover_Dynamic=login_hover.png
Value.Image.DynamicBtn_登录_Focus_Dynamic=login_hover.png
#取消
Value.Image.DynamicBtn_取消_Dynamic=exit_normal.png
Value.Image.DynamicBtn_取消_Hover_Dynamic=exit_hover.png
Value.Image.DynamicBtn_取消_Focus_Dynamic=exit_hover.png

#业务发起按钮
Value.Image.DynamicBtn_FaQi_Dynamic=faqi_normal.png
Value.Image.DynamicBtn_FaQi_Hover_Dynamic=faqi_hover.png
Value.Image.DynamicBtn_FaQi_Focus_Dynamic=faqi_hover.png
#系统整合按钮
Value.Image.DynamicBtn_ZhengHe_Dynamic=zhenghe_normal.png
Value.Image.DynamicBtn_ZhengHe_Hover_Dynamic=zhenghe_hover.png
Value.Image.DynamicBtn_ZhengHe_Focus_Dynamic=zhenghe_hover.png
#个性菜单按钮
Value.Image.DynamicBtn_GeXing_Dynamic=gexing_normal.png
Value.Image.DynamicBtn_GeXing_Hover_Dynamic=gexing_hover.png
Value.Image.DynamicBtn_GeXing_Focus_Dynamic=gexing_hover.png
#辅助工具按钮
Value.Image.DynamicBtn_Tool_Dynamic=tool_normal.png
Value.Image.DynamicBtn_Tool_Hover_Dynamic=tool_hover.png
Value.Image.DynamicBtn_Tool_Focus_Dynamic=tool_hover.png
#帮助按钮
Value.Image.DynamicBtn_Help_Dynamic=help_normal.png
Value.Image.DynamicBtn_Help_Hover_Dynamic=help_hover.png
Value.Image.DynamicBtn_Help_Focus_Dynamic=help_hover.png
#联网核查
Value.Image.DynamicBtn_Check_Dynamic=check_normal.png
Value.Image.DynamicBtn_Check_Hover_Dynamic=check_hover.png
Value.Image.DynamicBtn_Check_Focus_Dynamic=check_hover.png
#系统配置按钮
Value.Image.DynamicBtn_Config_Dynamic=sysconfig_normal.png
Value.Image.DynamicBtn_Config_Hover_Dynamic=sysconfig_hover.png
Value.Image.DynamicBtn_Config_Focus_Dynamic=sysconfig_hover.png
#返回按钮
Value.Image.DynamicBtn_Back_Dynamic=back_normal.png
Value.Image.DynamicBtn_Back_Hover_Dynamic=back_hover.png
Value.Image.DynamicBtn_Back_Focus_Dynamic=back_hover.png
#前进按钮
Value.Image.DynamicBtn_Next_Dynamic=next_normal.png
Value.Image.DynamicBtn_Next_Hover_Dynamic=next_hover.png
Value.Image.DynamicBtn_Next_Focus_Dynamic=next_hover.png

Value.Image.maxButtonNormal=maxButtonNormal.png
Value.Image.maxButtonHover=maxButtonHover.png
Value.Image.maxButtonClick=maxButtonClick.png
Value.Image.minButtonNormal=minButtonNormal.png
Value.Image.minButtonHover=minButtonHover.png
Value.Image.minButtonClick=minButtonClick.png
Value.Image.closeButtonNormal=closeButtonNormal.png
Value.Image.closeButtonHover=closeButtonHover.png
Value.Image.closeButtonClick=closeButtonClick.png
#Value.Image.titleBarBackground=titlebar.png
Value.Image.titleBarBackground=titlebarbackground.png
Value.Image.titlebar=titlebarbackground.png
Value.Image.titlebar1=titlebar_transparent.png
# 这个是配置abc最顶端的composite的背景
Value.Image.titlebar2=titleBarBackground3.png

#这个配置的是新型对话框中的按钮的三种背景
Value.Image.buttonNormal=ordinary.png
Value.Image.buttonHover=hover.png
Value.Image.buttonFocus=focus.png
Value.Image.buttonMouseDown=focus.png

Value.Image.错误图标=错误图标.png
Value.Image.警告图标=警告图标.png
Value.Image.确认图标=确认图标.png
Value.Image.消息图标=消息图标.png


Value.Color.ATreeNotChild=0,0,0
Value.Color.ATreeBackgroundSelected=31,162,210
Value.Color.ATreeBackgroundDefault=220,236,246
Value.Color.ATreeBackground=220,236,246
# 配置新型的多交易容器的相关属性
#Value.Color.MTCTabBackground=180,180,180
Value.Color.MTCTabBackground=238,238,238
Value.Color.MTCSelectedTabUnderlineRGB=48,196,243
Value.Color.MTCSelectedTabForeground=48,196,243
Value.Integer.MTCTabHeight=25
Value.Integer.MTCSelectedTabFontSize=9
Value.Integer.MTCUnSelectedTabFontSize=9
