#伪指令映射
#倍高
doubleHeight=^2
#倍宽
doubleWidth=^3
#倍高倍宽
doubleHW=^2^3
#取消倍高
cancelHeight=^a
#取消倍宽
cancelWidth=^b
#用户定义指令1
userDefined_order1=^m
#用户定义指令2
userDefined_order2=^n
#用户定义指令3
userDefined_order3=^g
#用户定义指令4
userDefined_order4=^h
#用户定义指令5
userDefined_order5=^k
#取消所有指令
cancelAllOrders=^a^f^e

#打印相关配置
#页边距(左)
leftMargin=0
#页边距(上)
topMargin=0
#中文字体
chFont=宋体,10
#西文字体
enFont=宋体,10
#列距
col_span=15,0
#行距
row_span=0
#倍高指令调整值
doubleHeightAdval=0
#倍宽指令调整值
doubleWidthAdval=0
#倍高倍宽指令调整值
doubleHWAdval=0
#用户定义指令1缩放比
userDefined_order1_ratio=1.3,1,1#0.7
#用户定义指令2缩放比
userDefined_order2_ratio=1,1,0#0
#用户定义指令3缩放比
userDefined_order3_ratio=0.8,1,0#0
#用户定义指令4缩放比
userDefined_order4_ratio=0.8,1,0#0
#用户定义指令5缩放比
userDefined_order5_ratio=0.8,1,0#0
