cn.com.agree.ab.communication/name=
cn.com.agree.ab.communication/type=bottom
cn.com.agree.ab.communication/parentConnectionUrl = tcp://172.21.30.11:30001
Platform/multiInstance=false
cn.com.agree.ab.communication/useMacCellName=false
Platform/theme=
