#Product Runtime Configuration File
osgi.splashPath=platform:/base/plugins/cn.com.agree.ab.client
eclipse.application=cn.com.agree.ab.client.app
eclipse.product=cn.com.agree.ab.client.product
osgi.bundles=org.eclipse.equinox.common@2:start,org.eclipse.update.configurator@3:start,org.eclipse.core.runtime@start
osgi.bundles.defaultStartLevel=4
