log4j.rootLogger=info, stdout
#log4j.rootLogger=debug, stdout

#ebbclient log
log4j.logger.cn.com.agree.ab.custom.ebb.client=, ebb
log4j.appender.ebb=cn.com.agree.commons.logging.RollingFileAppender
log4j.appender.ebb.File=log/cebClient.log
log4j.appender.ebb.layout=org.apache.log4j.PatternLayout
log4j.appender.ebb.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.ebb.bufferedIO=false
log4j.appender.ebb.MaxFileSize=1000KB
log4j.appender.ebb.MaxBackupIndex=10

#Communication log
log4j.logger.cn.com.agree.ab.communication=DEBUG, C
log4j.appender.C=cn.com.agree.commons.logging.RollingFileAppender
log4j.appender.C.File=log/communication.log
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.C.bufferedIO=false
log4j.appender.C.MaxFileSize=5000KB
log4j.appender.C.MaxBackupIndex=10

#Device log
log4j.logger.cn.com.agree.ab.device=DEBUG, D
log4j.appender.D=cn.com.agree.commons.logging.RollingFileAppender
log4j.appender.D.File=log/device.log
log4j.appender.D.layout=org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.D.bufferedIO=false
log4j.appender.D.MaxFileSize=1000KB
log4j.appender.D.MaxBackupIndex=10


#Resource log
log4j.logger.cn.com.agree.ab.resource=DEBUG, R
log4j.appender.R=cn.com.agree.commons.logging.RollingFileAppender
log4j.appender.R.File=log/resource.log
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{DATE} %5p %t %X{url} %c{1}:%M - %m%n
log4j.appender.R.bufferedIO=false
log4j.appender.R.MaxFileSize=1000KB
log4j.appender.R.MaxBackupIndex=10


# GUI log
log4j.logger.cn.com.agree.ab.gui=debug, gui
log4j.appender.gui=cn.com.agree.commons.logging.RollingFileAppender
log4j.appender.gui.File=log/gui.log
log4j.appender.gui.layout=org.apache.log4j.PatternLayout
log4j.appender.gui.layout.ConversionPattern=%d{dd-MM-yyyy HH:mm:ss,SSS} %5p %t <!--- %m --->%n
log4j.appender.gui.bufferedIO=false
log4j.appender.gui.MaxFileSize=1000KB
log4j.appender.gui.MaxBackupIndex=10
                                                    
